let mapleader = ","
syntax enable

" Colorschemes and stuff (the most important part of this vimrc)
set guifont=Monaco:h13
set t_Co=256
let g:solarized_termcolors=256
colors solarized " default colorscheme

" Configuration for vim-css-color
let g:cssColorVimDoNotMessMyUpdatetime = 1

" Toggle colorschemes <Leader>c
nnoremap <silent> <Leader>c :exec "color " .
    \ ((g:colors_name == "Tomorrow-Night-Eighties") ? "solarized" : "Tomorrow-Night-Eighties")<CR>

" Enable powerline (else only on split windows)
set laststatus=2

" Textformatting and stuff
set textwidth=80               " controls the wrap width
set formatoptions=cqt          " Automatic wrapping
set wrap                       " enables automatic wrapping of line
set wrapmargin=0

" Indentation
set backspace=indent,eol,start " allow backspacing over everything in insert mode

" Tabspecific options
filetype plugin indent on
set expandtab                  " Use spaces instead of tabs
set softtabstop=4              " a tab is 4 spaces
set shiftwidth=4               " number of spaces to use for autoindenting

" search options
set showmatch                  " set show matching parenthesis
set ignorecase                 " ignore case when searching
set smartcase                  " ignore case if search pattern is all lowercase,
                               " case-sensitive otherwise
" other options
set number                     " always show line numbers
set hlsearch                   " highlight search terms
set incsearch                  " show search matches as you type
set noswapfile                 " don´t create a swap file
set visualbell                 " turn off error sound

" For Xiki (Not completed yet)
" let $XIKI_DIR = "~/xiki"
" source $XIKI_DIR/etc/vim/xiki.vim

" For Pathogen (handle plugins)
set nocompatible
execute pathogen#infect()
syntax on
filetype plugin indent on

" Easy window navigation (thank god for this!)
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" I really hate that things don't auto-center
nmap G Gzz
nmap n nzz
nmap N Nzz
nmap } }zz
nmap { {zz

" EasyMotion setup
let g:EasyMotion_smartcase = 1  " enables smartcase search
nmap <Leader>l <Plug>(easymotion-lineforward)
nmap <Leader>j <Plug>(easymotion-j)zz
nmap <Leader>k <Plug>(easymotion-k)zz
nmap <Leader>h <Plug>(easymotion-linebackward)

" Ctags (To create ctags file 'ctags *'
set tags=./tags; " Tells Vim where to look for the tags file.
nnoremap <leader>. :CtrlPTag<cr>
nnoremap <silent> <Leader>b :TagbarToggle<CR>

" Toggle relative numbers <C-t>
function! NumberToggle()
    if(&relativenumber == 1)
        set norelativenumber
    else
        set relativenumber
    endif
endfunc
nnoremap <C-t> :call NumberToggle()<cr>

" Highlight any text that surpasses the given value
"augroup vimrc_autocmds
  "autocmd BufEnter * highlight OverLength
                    "\ ctermbg=236 guibg=#303030
  "autocmd BufEnter * match OverLength /\%81v.*/
"augroup END

" open Nerdtree automatically when starting up
"autocmd vimenter * NERDTree

" apperance of directory in Explore
"let g:netrw_liststyle=3

" Formatting options
au BufNewFile,BufRead *.ejs set filetype=html " read ejs as html

" Mappings
map <Leader>n :NERDTreeToggle<CR> " (Nerdtree)
cnoremap fw :FixWhitespace " (FixWhitespace)
map <Leader>p :CtrlPClearAllCaches " (clear cache for CtrlP)

"""" Plugins

" CtrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Syntactis
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0 " Turn off quickfix messages
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
